using LockIn;
static class Tests {
 static int count;static void Check(bool condition,string name){if(!condition)throw new Exception("Failed: "+name);count++;}
 static void Main(){var now=DateTimeOffset.UtcNow;var folder=Path.Combine(Path.GetTempPath(),"lockin-tests-"+Guid.NewGuid());try{
  var s=new Session{End=now.AddMinutes(10),Planned=600};Policy.AddTime(s,5,now);Check(s.End==now.AddMinutes(15)&&s.Planned==900,"active extension");s.End=null;s.PausedRemaining=120;Policy.AddTime(s,2,now);Check(s.PausedRemaining==240&&s.End==null,"paused extension");s.PausedRemaining=null;s.Waiting=true;s.End=now.AddMinutes(-1);Policy.AddTime(s,1,now);Check(s.Planned==1080,"waiting extension");
  s.Rules.Indefinite=true;try{Policy.AddTime(s,1,now);throw new Exception("accepted indefinite");}catch(InvalidOperationException){count++;}
  Check(Policy.Normalize("https://YouTube.com:443/watch") == "youtube.com","normalize URL");foreach(var bad in new[]{"","two words","file:///a","https://user:pass@example.com","*.example.com","a..com","bücher.de"})Check(Policy.Normalize(bad)==null,"reject domain "+bad);
  Check(Policy.Matches("docs.example.com","example.com")&&!Policy.Matches("badexample.com","example.com"),"domain boundaries");
  var e=new Engine(folder);Check(e.Data.Presets.Count==0,"no presets by default");e.Setup.Apps.Add(new(){Path=@"C:\Apps\a.exe"});e.Start();var id=e.Data.Session!.Id;Check(!Policy.AllowsApp(@"c:\apps\A.exe",e.Data.Session,Array.Empty<AppRule>(),now),"case-insensitive executable rules");Check(Policy.AllowsApp(@"C:\Apps\a.exe",e.Data.Session,new[]{new AppRule{Path=@"C:\Apps\a.exe"}},now),"always allow wins");e.PauseOrResume();Check(e.Data.Session.PausedRemaining.HasValue&&!e.Active,"pause unblocks");e.AddTime(5);var paused=e.Data.Session.PausedRemaining;var recovered=new Engine(folder);Check(recovered.Data.Session!.Id==id&&recovered.Data.Session.PausedRemaining==paused,"paused timer persisted");e.PauseOrResume();Check(e.Active,"resume");e.Stop();Check(e.Data.Session==null&&e.Data.History.Count==1,"normal stop history");
  e.Setup.Nuclear=true;e.Authenticate=()=>false;e.Consent=_=>true;e.Start();Check(e.Data.Session==null,"auth rejection blocks nuclear");e.Authenticate=()=>true;e.AskFutureAuthentication=()=>true;e.Start();Check(e.Nuclear&&e.Data.RequireAuthentication,"verified nuclear");var end=e.Data.Session!.End;e.Authenticate=()=>false;e.AddTime(5);Check(e.Data.Session.End==end,"denied time auth");e.Authenticate=()=>true;e.AddTime(5);Check(e.Data.Session.End==end!.Value.AddMinutes(5),"nuclear extends after auth");try{e.PauseOrResume();throw new Exception("paused nuclear");}catch(InvalidOperationException){count++;}
  e.Challenge=_=>false;e.Stop();Check(e.Data.Session!=null&&Policy.RemainingExits(e.Data,now)==2,"failed challenge does not spend quota");e.Challenge=_=>true;e.Stop();Check(Policy.RemainingExits(e.Data,now)==1,"successful exit spends once");e.Start();e.Stop();Check(Policy.RemainingExits(e.Data,now)==0,"second monthly exit");e.Start();try{e.Stop();throw new Exception("third emergency exit");}catch(InvalidOperationException){count++;}
  Check(Policy.RemainingExits(e.Data,now.AddMonths(1))==2,"next month quota");
  e.Data.Session=null;e.Setup.Nuclear=false;e.Setup.ExitFriction=true;e.Start();e.Challenge=_=>false;e.PauseOrResume();Check(e.Active,"pause friction leaves focus running");e.FinishChallenge(e.Data.Session!.Id,"pause");Check(e.Data.Session.PausedRemaining.HasValue,"passed native pause challenge");var other=Guid.NewGuid();e.FinishChallenge(other,"stop");Check(e.Data.Session!=null,"stale challenge cannot stop another session");e.Challenge=_=>true;e.Stop();
  e.Setup.TimerMode="pomodoro";e.Setup.AutoStart=false;e.Setup.ExitFriction=false;e.Start();e.Data.Session!.End=now.AddSeconds(-1);e.Tick();Check(e.Data.Session!.Waiting&&e.Data.Session.Phase=="shortBreak"&&!e.Active,"pomodoro waiting break");e.StartWaiting();e.SkipBreak();Check(e.Active&&e.Data.Session.Phase=="focus","skip break starts focus");
  e.Stop();e.Setup.TimerMode="focus";e.Setup.Indefinite=true;e.Setup.Nuclear=true;e.Start();Check(e.Data.Session!.Indefinite&&!e.Nuclear&&!e.Data.Session.Friction,"indefinite has no nuclear or friction");
  Console.WriteLine($"{count} core checks passed.");
 }finally{if(Directory.Exists(folder))Directory.Delete(folder,true);}}
}
