using System.Windows;
using System.Windows.Controls;
using System.Windows.Threading;
namespace LockIn;
public sealed class MainWindow:Window {
 readonly Engine engine;readonly StackPanel panel=Theme.Stack();readonly TextBlock timer=Theme.Text("",64),phase=Theme.Text("",14,Theme.Muted),nuclear=Theme.Text("",13,Theme.Purple);readonly ComboBox presets=new();readonly WrapPanel controls=new();readonly Button quit;bool updating;
 public SyncServer? Server;public Action? Quit;ExitWindow? exitWindow;
 public MainWindow(Engine engine){this.engine=engine;Theme.Window(this,"LockIn",620,660);MinWidth=470;
  panel.Children.Add(Theme.Text("LOCKIN",13,Theme.Purple));var modes=new StackPanel{Orientation=Orientation.Horizontal};modes.Children.Add(Theme.Button("Focus",()=>SetMode("focus")));modes.Children.Add(Theme.Button("Pomodoro",()=>SetMode("pomodoro")));panel.Children.Add(modes);
  panel.Children.Add(phase);panel.Children.Add(timer);panel.Children.Add(nuclear);presets.Margin=new Thickness(0,10,0,10);presets.SelectionChanged+=(_,_)=>{if(updating||engine.Data.Session!=null)return;engine.Transaction(()=>engine.Data.Selected=presets.SelectedIndex<=0?null:engine.Data.Presets[presets.SelectedIndex-1].Id);};panel.Children.Add(presets);
  var editRow=new WrapPanel();editRow.Children.Add(Theme.Button("✎ Edit settings",()=>new RuleEditor(engine,this).ShowDialog()));editRow.Children.Add(Theme.Button("Manage presets…",ManagePresets));panel.Children.Add(editRow);panel.Children.Add(controls);
  var duration=new WrapPanel();duration.Children.Add(Theme.Button("Set minutes…",()=>{if(engine.Data.Session!=null)return;var text=Theme.Prompt(this,"Focus duration (1–180 minutes)",engine.Setup.Focus.ToString());if(text==null)return;if(!int.TryParse(text,out var n)||n is <1 or >180)throw new InvalidOperationException("Enter 1–180 minutes.");engine.Transaction(()=>{engine.Setup.Focus=n;engine.Setup.Indefinite=false;});}));duration.Children.Add(Theme.Button("Timed / Indefinite",()=>{if(engine.Data.Session!=null||engine.Setup.TimerMode!="focus")return;engine.Transaction(()=>{engine.Setup.Indefinite=!engine.Setup.Indefinite;if(engine.Setup.Indefinite){engine.Setup.Nuclear=false;engine.Setup.ExitFriction=false;}});}));panel.Children.Add(duration);
  panel.Children.Add(Theme.Button("Browsers & preferences",Preferences));panel.Children.Add(Theme.Button("Session history",History));quit=Theme.Button("Quit LockIn",()=>Quit?.Invoke());panel.Children.Add(quit);Content=new ScrollViewer{Content=panel,VerticalScrollBarVisibility=ScrollBarVisibility.Auto};engine.Changed+=Refresh;Refresh();
  engine.Authenticate=()=>WindowsSecurity.Verify(this);engine.AskFutureAuthentication=()=>MessageBox.Show(this,"Require your Windows account password each time you start Nuclear Mode or add time to it?","Nuclear verification",MessageBoxButton.YesNo)==MessageBoxResult.Yes;engine.Consent=text=>MessageBox.Show(this,text,"LockIn",MessageBoxButton.YesNo)==MessageBoxResult.Yes;
  engine.Challenge=action=>{Show();Activate();if(exitWindow==null){exitWindow=new ExitWindow(engine,this,action);exitWindow.Closed+=(_,_)=>exitWindow=null;exitWindow.Show();}else exitWindow.Activate();return false;};
 }
 void SetMode(string value){if(engine.Data.Session!=null)return;engine.Transaction(()=>{engine.Setup.TimerMode=value;if(value=="pomodoro")engine.Setup.Indefinite=false;});}
 public void Refresh(){var s=engine.Data.Session;var rules=engine.Rules;phase.Text=(rules.TimerMode=="pomodoro"?"Pomodoro":"Focus")+" · "+(s==null?"Ready":s.Waiting?"Ready for "+s.Phase:s.PausedRemaining.HasValue?"Paused":s.Phase=="focus"?"Focusing":s.Phase=="longBreak"?"Long break":"Short break");timer.Text=s==null?(rules.TimerMode=="focus"&&rules.Indefinite?"∞":Theme.Clock(rules.Focus*60)):s.Indefinite?Theme.Clock(s.Elapsed(DateTimeOffset.UtcNow)):Theme.Clock(s.Remaining(DateTimeOffset.UtcNow));nuclear.Text=(s?.Nuclear??rules.Nuclear)&&!(rules.TimerMode=="focus"&&rules.Indefinite)?$"Nuclear Mode · {Policy.RemainingExits(engine.Data,DateTimeOffset.UtcNow)} emergency exits this month":"";
  updating=true;presets.Items.Clear();presets.Items.Add("Custom");foreach(var preset in engine.Data.Presets)presets.Items.Add(preset.Name);presets.SelectedIndex=engine.Data.Selected==null?0:engine.Data.Presets.FindIndex(x=>x.Id==engine.Data.Selected)+1;presets.IsEnabled=s==null;updating=false;
  quit.Visibility=s==null?Visibility.Visible:Visibility.Collapsed;controls.Children.Clear();if(s==null){controls.Children.Add(Theme.Button("Start Focus",engine.Start));}else{if(s.Waiting)controls.Children.Add(Theme.Button("Start next phase",engine.StartWaiting));else if(!engine.Nuclear)controls.Children.Add(Theme.Button(s.PausedRemaining.HasValue?"Resume":"Pause",engine.PauseOrResume));controls.Children.Add(Theme.Button(engine.Nuclear?"Emergency exit":"Stop",engine.Stop,!engine.Nuclear||Policy.RemainingExits(engine.Data,DateTimeOffset.UtcNow)>0));if(!s.Indefinite)controls.Children.Add(Theme.Button("Add time…",AddTime));if(s.Phase!="focus")controls.Children.Add(Theme.Button("Skip break",engine.SkipBreak));}
 }
 public void RefreshClock(){var s=engine.Data.Session;if(s!=null)timer.Text=Theme.Clock(s.Indefinite?s.Elapsed(DateTimeOffset.UtcNow):s.Remaining(DateTimeOffset.UtcNow));}
 public void AddTime(){if(engine.Data.Session==null||engine.Data.Session.Indefinite)return;var input=Theme.Prompt(this,"Add time (1–180 minutes)","5");if(input==null)return;if(!int.TryParse(input,out var n)||n is <1 or >180)throw new InvalidOperationException("Enter 1–180 minutes.");engine.AddTime(n);}
 void ManagePresets(){if(engine.Nuclear)return;var w=new Window{Owner=this};Theme.Window(w,"Manage presets",520,460);var p=Theme.Stack();p.Children.Add(Theme.Text("Printing-style presets",22));p.Children.Add(Theme.Text("Save the current settings, replace a preset, rename, duplicate or delete it."));var list=Theme.Select("Choose a preset…");foreach(var item in engine.Data.Presets)list.Items.Add(item.Name);p.Children.Add(list);Preset? Selected()=>list.SelectedIndex>0?engine.Data.Presets.ElementAtOrDefault(list.SelectedIndex-1):null;
  p.Children.Add(Theme.Button("Save current as new preset…",()=>{var name=Theme.Prompt(w,"Preset name");if(name==null)return;engine.Transaction(()=>{var preset=Engine.Copy(engine.Rules);preset.Id=Guid.NewGuid();preset.Name=name;engine.Data.Presets.Add(preset);if(engine.Data.Session==null)engine.Data.Selected=preset.Id;});w.Close();}));
  p.Children.Add(Theme.Button("Save current into selected preset",()=>{var selected=Selected()??throw new InvalidOperationException("Choose a preset.");engine.Transaction(()=>{var copy=Engine.Copy(engine.Rules);copy.Id=selected.Id;copy.Name=selected.Name;engine.Data.Presets[engine.Data.Presets.IndexOf(selected)]=copy;});w.Close();}));
  p.Children.Add(Theme.Button("Rename…",()=>{var selected=Selected()??throw new InvalidOperationException("Choose a preset.");var name=Theme.Prompt(w,"Preset name",selected.Name);if(name!=null)engine.Transaction(()=>selected.Name=name);w.Close();}));
  p.Children.Add(Theme.Button("Duplicate…",()=>{var selected=Selected()??throw new InvalidOperationException("Choose a preset.");var name=Theme.Prompt(w,"Preset name",selected.Name+" copy");if(name==null)return;engine.Transaction(()=>{var copy=Engine.Copy(selected);copy.Id=Guid.NewGuid();copy.Name=name;engine.Data.Presets.Add(copy);});w.Close();}));
  p.Children.Add(Theme.Button("Delete",()=>{var selected=Selected()??throw new InvalidOperationException("Choose a preset.");if(MessageBox.Show(w,"Delete "+selected.Name+"?","LockIn",MessageBoxButton.YesNo)!=MessageBoxResult.Yes)return;engine.Transaction(()=>{engine.Data.Presets.Remove(selected);if(engine.Data.Selected==selected.Id)engine.Data.Selected=null;});w.Close();}));w.Content=p;w.ShowDialog();
 }
 void History(){var w=new Window{Owner=this};Theme.Window(w,"Session history",540,520);var p=Theme.Stack();p.Children.Add(Theme.Text("Your focus time",24));p.Children.Add(Theme.Text($"{Math.Round(engine.Data.History.Sum(x=>x.Seconds)/60)} total minutes"));foreach(var item in engine.Data.History.AsEnumerable().Reverse().Take(200))p.Children.Add(Theme.Text($"{item.Date:g} · {item.Name} · {Math.Round(item.Seconds/60)} min · {(item.Completed?"Completed":"Ended early")}",13));w.Content=new ScrollViewer{Content=p};w.ShowDialog();}
 void Preferences(){var w=new Window{Owner=this};Theme.Window(w,"Browsers & preferences",580,680);var p=Theme.Stack();p.Children.Add(Theme.Text("Connect your browsers",23));p.Children.Add(Theme.Text(Server?.Status??"Starting…"));p.Children.Add(Theme.Text("Click Connect Automatically in the extension. LockIn opens a confirmation. You can use a short-lived code instead."));var code=Theme.Text("");p.Children.Add(code);p.Children.Add(Theme.Button("Create backup pairing code",()=>{Server?.NewCode();code.Text="Code: "+Server?.Code+" · expires in 2 minutes";}));foreach(var c in Server?.Credentials.ToArray()??Array.Empty<BrowserCredential>())p.Children.Add(Theme.Button(c.Name+" · Disconnect",()=>{Server?.Disconnect(c);w.Close();},!engine.Active));
  p.Children.Add(Theme.Text("Always allowed",18));p.Children.Add(Theme.Text("These apps and sites bypass blocking. Changes are locked during Nuclear Mode.",12,Theme.Muted));var sites=Theme.Input(string.Join(Environment.NewLine,engine.Data.NeverDomains));sites.AcceptsReturn=true;sites.MinHeight=70;sites.IsEnabled=!engine.Nuclear;p.Children.Add(Theme.Text("One website per line",12));p.Children.Add(sites);var neverApps=Engine.Copy(engine.Data.NeverApps);var apps=new StackPanel();void Render(){apps.Children.Clear();foreach(var a in neverApps.ToArray())apps.Children.Add(Theme.Button(a.Name+" · Remove",()=>{neverApps.Remove(a);Render();},!engine.Nuclear));}Render();p.Children.Add(apps);p.Children.Add(Theme.Button("Add always-allowed app…",()=>{var d=new Microsoft.Win32.OpenFileDialog{Filter="Applications|*.exe"};if(d.ShowDialog(w)==true&&!neverApps.Any(a=>Policy.SamePath(a.Path,d.FileName))){neverApps.Add(new(){Path=d.FileName,Name=Path.GetFileNameWithoutExtension(d.FileName)});Render();}},!engine.Nuclear));
  var auth=Theme.Check("Require Windows password for Nuclear starts / added time",engine.Data.RequireAuthentication);auth.IsEnabled=!engine.Nuclear;p.Children.Add(auth);var nf=Theme.Check("Notify when Focus starts",engine.Data.NotifyFocus);var ns=Theme.Check("Notify when a short break starts",engine.Data.NotifyShort);var nl=Theme.Check("Notify when a long break starts",engine.Data.NotifyLong);p.Children.Add(nf);p.Children.Add(ns);p.Children.Add(nl);
  p.Children.Add(Theme.Button("Save preferences",()=>{var parsed=sites.Text.Split(new[]{'\r','\n'},StringSplitOptions.RemoveEmptyEntries).Select(x=>Policy.Normalize(x)??throw new InvalidOperationException("Invalid always-allowed website: "+x)).Distinct().ToList();if(parsed.Count>2000)throw new InvalidOperationException("Limit always-allowed websites to 2,000 domains.");if(!engine.Nuclear&&engine.Data.RequireAuthentication!=auth.IsChecked&&engine.Data.NuclearVerified&&!WindowsSecurity.Verify(w))return;engine.Transaction(()=>{if(!engine.Nuclear){engine.Data.NeverDomains=parsed;engine.Data.NeverApps=neverApps;engine.Data.RequireAuthentication=auth.IsChecked==true;}engine.Data.NotifyFocus=nf.IsChecked==true;engine.Data.NotifyShort=ns.IsChecked==true;engine.Data.NotifyLong=nl.IsChecked==true;});w.Close();}));w.Content=new ScrollViewer{Content=p,VerticalScrollBarVisibility=ScrollBarVisibility.Auto};w.ShowDialog();}
}
