using System.Windows;
using System.Windows.Controls;
using Microsoft.Win32;
namespace LockIn;
public sealed class RuleEditor:Window {
 readonly Engine engine;readonly Preset draft;readonly StackPanel p=Theme.Stack();readonly ComboBox mode;readonly CheckBox strict,ai,nuclear,friction,auto;readonly TextBox focus,shortBreak,longBreak,cycles;readonly StackPanel apps=new(),domains=new(),extra=new();
 public RuleEditor(Engine engine,Window owner){this.engine=engine;draft=Engine.Copy(engine.Rules);Owner=owner;Theme.Window(this,"Edit · "+draft.Name,620,740);p.Children.Add(Theme.Text("Customize your Focus",25));
  if(engine.Nuclear){p.Children.Add(Theme.Text("Rules are locked during Nuclear Mode. You can still add time from the main window."));p.Children.Add(Theme.Button("Done",Close));Content=p;mode=Theme.Select();strict=ai=nuclear=friction=auto=Theme.Check("",false);focus=shortBreak=longBreak=cycles=Theme.Input("");return;}
  mode=Theme.Select("Block selected apps and sites","Only allow selected apps and sites");mode.SelectedIndex=draft.Mode=="onlyAllow"?1:0;p.Children.Add(Theme.Text("App and website rules",18));p.Children.Add(mode);
  p.Children.Add(Theme.Text("Applications",18));p.Children.Add(apps);p.Children.Add(Theme.Button("Add .exe…",()=>{var dialog=new OpenFileDialog{Filter="Applications (*.exe)|*.exe",Multiselect=true};if(dialog.ShowDialog(this)==true)foreach(var file in dialog.FileNames)AddApp(file);RenderApps();}));
  var running=Theme.Select("Choose a running app…");var runningApps=Blocker.Applications();foreach(var app in runningApps)running.Items.Add(app.Name);running.SelectionChanged+=(_,_)=>{if(running.SelectedIndex>0){var app=runningApps[running.SelectedIndex-1];AddApp(app.Path);RenderApps();running.SelectedIndex=0;}};p.Children.Add(running);
  p.Children.Add(Theme.Text("Websites",18));p.Children.Add(Theme.Text("Enter example.com or https://example.com. Subdomains are included.",12,Theme.Muted));p.Children.Add(domains);AddDomainInput(draft.Domains,domains);
  ai=Theme.Check("Block AI sites and hide Google AI results",draft.BlockAI);p.Children.Add(ai);p.Children.Add(Theme.Text("Additional AI domains",14));p.Children.Add(extra);AddDomainInput(draft.ExtraAI,extra);
  strict=Theme.Check("Strict app blocking · hide Quit App on app shields",draft.Strict);p.Children.Add(strict);
  nuclear=Theme.Check("Nuclear Mode · no pause or rule changes",draft.Nuclear);if(draft.TimerMode=="focus"&&draft.Indefinite)nuclear.Visibility=Visibility.Collapsed;p.Children.Add(nuclear);
  friction=Theme.Check("Require attention check for pausing or stopping",draft.ExitFriction);if(draft.TimerMode=="focus"&&draft.Indefinite)friction.Visibility=Visibility.Collapsed;p.Children.Add(friction);
  p.Children.Add(Theme.Text("Timers (minutes)",18));focus=Number("Focus",draft.Focus);shortBreak=Number("Short break",draft.ShortBreak);longBreak=Number("Long break",draft.LongBreak);cycles=Number("Cycles before long break",draft.Cycles);auto=Theme.Check("Start the next Pomodoro phase automatically",draft.AutoStart);p.Children.Add(auto);
  if(engine.Data.Session!=null){nuclear.IsEnabled=false;friction.IsEnabled=false;focus.IsEnabled=shortBreak.IsEnabled=longBreak.IsEnabled=cycles.IsEnabled=auto.IsEnabled=false;p.Children.Add(Theme.Text("Live edits change apps, sites, rule mode, AI and strict blocking. Timer and exit settings stay with the running session.",12,Theme.Muted));}
  nuclear.Checked+=(_,_)=>{friction.IsChecked=true;friction.IsEnabled=false;};nuclear.Unchecked+=(_,_)=>friction.IsEnabled=engine.Data.Session==null;if(nuclear.IsChecked==true){friction.IsChecked=true;friction.IsEnabled=false;}
  p.Children.Add(Theme.Button("Save changes",Save));p.Children.Add(Theme.Button("Cancel",Close));Content=new ScrollViewer{Content=p,VerticalScrollBarVisibility=ScrollBarVisibility.Auto};RenderApps();RenderDomains(draft.Domains,domains);RenderDomains(draft.ExtraAI,extra);
 }
 TextBox Number(string label,int value){p.Children.Add(Theme.Text(label,12));var box=Theme.Input(value.ToString());p.Children.Add(box);return box;}
 void AddApp(string file){if(!draft.Apps.Any(a=>Policy.SamePath(a.Path,file)))draft.Apps.Add(new(){Path=System.IO.Path.GetFullPath(file),Name=System.IO.Path.GetFileNameWithoutExtension(file)});}
 void RenderApps(){apps.Children.Clear();foreach(var app in draft.Apps.ToArray()){var row=new StackPanel{Orientation=Orientation.Horizontal};row.Children.Add(Theme.Button("Remove",()=>{draft.Apps.Remove(app);RenderApps();}));row.Children.Add(Theme.Text(app.Name));apps.Children.Add(row);}}
 void AddDomainInput(List<string> list,StackPanel target){var box=Theme.Input("");box.ToolTip="example.com or https://example.com";p.Children.Add(box);p.Children.Add(Theme.Button("Add website",()=>{var domain=Policy.Normalize(box.Text)??throw new InvalidOperationException("Enter a valid domain or HTTP(S) URL.");if(!list.Contains(domain))list.Add(domain);box.Text="";RenderDomains(list,target);}));}
 static void RenderDomains(List<string> list,StackPanel target){target.Children.Clear();foreach(var item in list.ToArray()){var row=new StackPanel{Orientation=Orientation.Horizontal};row.Children.Add(Theme.Button("Remove",()=>{list.Remove(item);RenderDomains(list,target);}));row.Children.Add(Theme.Text(item));target.Children.Add(row);}}
 void Save(){if(draft.Domains.Count>2000||draft.ExtraAI.Count>400)throw new InvalidOperationException("Limit website rules to 2,000 domains and extra AI rules to 400 domains.");if(engine.Nuclear)throw new InvalidOperationException("Rules are locked.");draft.Mode=mode.SelectedIndex==1?"onlyAllow":"block";draft.Strict=strict.IsChecked==true;draft.BlockAI=ai.IsChecked==true;
  if(engine.Data.Session==null){draft.Nuclear=nuclear.Visibility==Visibility.Visible&&nuclear.IsChecked==true;draft.ExitFriction=friction.Visibility==Visibility.Visible&&friction.IsChecked==true;draft.AutoStart=auto.IsChecked==true;draft.Focus=Parse(focus,1,180);draft.ShortBreak=Parse(shortBreak,1,120);draft.LongBreak=Parse(longBreak,1,120);draft.Cycles=Parse(cycles,1,12);}
  engine.Transaction(()=>{if(engine.Data.Session is {} s){s.Rules.Mode=draft.Mode;s.Rules.Apps=draft.Apps;s.Rules.Domains=draft.Domains;s.Rules.ExtraAI=draft.ExtraAI;s.Rules.BlockAI=draft.BlockAI;s.Rules.Strict=draft.Strict;}else if(engine.Data.Selected is {} id){var index=engine.Data.Presets.FindIndex(x=>x.Id==id);if(index>=0)engine.Data.Presets[index]=draft;}else engine.Data.Custom=draft;});Close();
 }
 static int Parse(TextBox box,int min,int max)=>int.TryParse(box.Text,out var n)&&n>=min&&n<=max?n:throw new InvalidOperationException($"Enter a whole number from {min} to {max}.");
}
